---
kind: Application
metadata:
  name: Task5
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    path: Task5
    repoURL: https://pkupryianau.github.io/rsschool_task5/
    targetRevision: test
    helm:
      valueFiles:
      - values.yaml```
